In [3]:
import pandas as pd
import yfinance as yf
from pathlib import Path
import os
import numpy as np

Goals
- remove NA and check quality
- filter companies by news volume
- clean company (name) column

In [4]:
cwd_path = Path(os.getcwd())

In [5]:
try_file = cwd_path / 'data' / 'raw' / 'sentiment_all.csv'

In [6]:
download_csv = try_file if os.path.exists(try_file) else print('File not found.')

In [7]:
sent_df_raw = pd.read_csv(download_csv, header= 'infer')

In [8]:
sent_df_raw.head()

,date,company,volume,positive,negative,sentiment,esg_score,e_score,s_score,g_score,general_risk_score,esg_risk_score,credit_risk_score,immediate_risk_score,ISIN
0,2010-01-01,company:cara_therapeutics_inc,0,0,0,0.5,5.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0,US1407551092
1,2010-01-02,company:cara_therapeutics_inc,0,0,0,0.5,5.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0,US1407551092
2,2010-01-03,company:cara_therapeutics_inc,0,0,0,0.5,5.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0,US1407551092
3,2010-01-04,company:cara_therapeutics_inc,0,0,0,0.5,5.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0,US1407551092
4,2010-01-05,company:cara_therapeutics_inc,0,0,0,0.5,5.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0,US1407551092

In [9]:
def clean_company(ser : pd.Series, sep : str):
    return ser.split(sep)[1]

In [10]:
sent_df = sent_df_raw.copy()

In [13]:
sent_df.replace({'carnival___plc':'carnival_plc'}, inplace= True)

In [14]:
sent_df.query("company == 'carnival_plc'").head()

,date,company,volume,positive,negative,sentiment,esg_score,e_score,s_score,g_score,general_risk_score,esg_risk_score,credit_risk_score,immediate_risk_score,ISIN
10364,2010-01-01,carnival_plc,0,0,0,0.5,5.0,5.0,5.0,5.0,9.990004,0.0,9.989678,0.0,US14365C1036
10365,2010-01-02,carnival_plc,0,0,0,0.5,5.0,5.0,5.0,5.0,9.990004,0.0,9.989677,0.0,US14365C1036
10366,2010-01-03,carnival_plc,0,0,0,0.5,5.0,5.0,5.0,5.0,9.990004,0.0,9.989677,0.0,US14365C1036
10367,2010-01-04,carnival_plc,1,0,0,0.5,5.0,5.0,5.0,5.0,9.990004,0.0,9.989677,0.0,US14365C1036
10368,2010-01-05,carnival_plc,1,0,0,0.5,5.0,5.0,5.0,5.0,9.990004,0.0,9.989677,0.0,US14365C1036

In [16]:
# sent_df.to_csv(cwd_path / 'data' / 'cleaned' / 'sentiment_all_cleaned.csv', index= False)